name: Create Archive
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'LiveTL.zip'
        path: "LiveTL"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: LiveTL.zip
        asset_name: LiveTL.zip
        tag: ${{ github.ref }}
        overwrite: true
