name: Latest Release Build
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package extensions
        run: make EMBED_DOMAIN=https://kentonishi.github.io/LiveTL/embed VERSION=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g') all
      - name: Set gradle version
        run: make android-release EMBED_DOMAIN=https://kentonishi.github.io/LiveTL/embed VERSION=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g')
      - name: Install zipalign and apksigner
        run: sudo apt install zipalign apksigner
      - name: Upload Chrome package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/chrome/LiveTL.zip
          asset_name: LiveTL-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Firefox package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/firefox/LiveTL.zip
          asset_name: LiveTL-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: |
          pushd LiveTL-Android
          bash ./gradlew assemble
          popd
          pushd LiveTL-Android/app/build/outputs/apk/release
          zipalign -v -p 4 app-release-unsigned.apk app-release-unsigned-aligned.apk
          echo ${{ secrets.KEY_B64 }} | base64 --decode >> my-release-key.jks
          apksigner sign --ks my-release-key.jks --out app-release-signed.apk app-release-unsigned-aligned.apk
          popd
      - name: Upload Android APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LiveTL-Android/app/build/outputs/apk/release/app-release-signed.apk
          asset_name: LiveTL-Android.apk
          tag: ${{ github.ref }}
          overwrite: true
